### ISSUE TITLE
Cmake error:FindFreetype

### ISSUE THREAD

**Issue by mingyEx** [lukedan/codepad#3]
Hello, I did not find the *.sln file.
I installed rapidjson with vcpkg, and then encountered the following problems.
```shell
CMake Error at C:/Program Files/CMake/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Freetype (missing: FREETYPE_LIBRARY FREETYPE_INCLUDE_DIRS)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.15/Modules/FindFreetype.cmake:157 (find_package_handle_standard_args)
  CMakeLists.txt:125 (find_package)

```
but I am sure I has install the freetype library with both 32 and 64bit version using vcpkg.
windows10, vs2019.
Any hints are greatly appreciated

**Comment by lukedan** [comment]
Hi @mingy532,

I doubt that this is a problem with the CMake script since FindFreetype is provided by CMake itself. There are a few things you may want to double-check:
- The vcpkg documentation says:

  > In order to use vcpkg with CMake outside of an IDE, you can use the toolchain file:
  > ```
  > cmake -B [build directory] -S . -DCMAKE_TOOLCHAIN_FILE=[path to vcpkg]/scripts/buildsystems/vcpkg.cmake
  > cmake --build [build directory]
  > ```

  Make sure you have that `CMAKE_TOOLCHAIN_FILE` definition or CMake won't be able to find vcpkg packages. If you're using Visual Studio for CMake with the vcpkg integration installed it should add that for you.

- If you're still having trouble, you can specify `-DUSE_CAIRO=No` during configuration to completely disable the Cairo backend and remove the dependency on these packages. The Cairo backend does not perform very well on Windows so you probably won't need it.

- Finally, if you *really* want to have that backend, you can try manually changing the FreeType paths. It's easier to do it in cmake-gui.

On a side note, you may want to also run `git submodule update --init --recursive` to make sure the tree-sitter plugin builds successfully.

**Comment by mingy532** [comment]
Sorry I don't understand cmake.
Can you tell me what is mentioned here
```bash
cmake -B [build directory] -S. -DCMAKE_TOOLCHAIN_FILE=[path to vcpkg]/scripts/buildsystems/vcpkg.cmake
cmake --build [build directory]
```
What format should it be, I tried
```bash
cmake -B C:/Users/xxx/Desktop/codepad -S -DUSE_CAIRO=No. -DCMAKE_TOOLCHAIN_FILE=C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake
```
But an error
```
CMake Error: No source directory specified for -S
```

**Comment by mingy532** [comment]
and I don't know where to type the "-DUSE_CAIRO=No"。。

**Comment by mingyEx** [comment]
thanks,it work well.
